import { MinusIcon, PaintBucketIcon, PaletteIcon, SquareDashedIcon, SquareRoundCornerIcon } from 'lucide-react'
import { z } from 'zod'

export const zAppearanceSchema = z.object({
  color: z.string().optional(),
  backgroundColor: z.string().optional(),
  borderColor: z.string().optional(),
  borderWidth: z.number().optional(),
  borderStyle: z.enum(['solid', 'dashed', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset']).optional(),
  borderTopLeftRadius: z.number().optional(),
  borderTopRightRadius: z.number().optional(),
  borderBottomLeftRadius: z.number().optional(),
  borderBottomRightRadius: z.number().optional(),
  borderTopLeftRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderTopRightRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderBottomLeftRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderBottomRightRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
})

export type AppearanceSchema = z.infer<typeof zAppearanceSchema>

export const AppearanceGroups = [
  {
    legend: 'Colors',
    components: [
      {
        label: 'Color',
        name: 'color',
        type: 'input',
        inputType: 'color',
        icon: PaletteIcon,
        placeholder: '#000000',
        defaultValue: '#000000',
      },
      {
        label: 'Background Color',
        name: 'backgroundColor',
        type: 'input',
        inputType: 'color',
        icon: PaintBucketIcon,
        placeholder: '#000000',
        defaultValue: '#000000',
      },
    ],
  },
  {
    legend: 'Border',
    components: [
      {
        label: 'Border Color',
        name: 'borderColor',
        type: 'input',
        inputType: 'color',
        icon: PaintBucketIcon,
        placeholder: '#000000',
        defaultValue: '#000000',
      },
      {
        label: 'Border Width',
        name: 'borderWidth',
        type: 'input',
        inputType: 'number',
        icon: MinusIcon,
        placeholder: '0',
        defaultValue: 0,
        min: 0,
      },
      {
        label: 'Border Style',
        name: 'borderStyle',
        type: 'select',
        defaultValue: 'solid',
        icon: SquareDashedIcon,
        options: [
          { label: 'Solid', value: 'solid' },
          { label: 'Dashed', value: 'dashed' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Double', value: 'double' },
          { label: 'Groove', value: 'groove' },
          { label: 'Ridge', value: 'ridge' },
          { label: 'Inset', value: 'inset' },
          { label: 'Outset', value: 'outset' },
        ],
      },
      {
        label: 'Border Top Left Radius',
        name: 'borderTopLeftRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderTopLeftRadiusUnit',
        selectLabel: 'Unit',
        icon: SquareRoundCornerIcon,
        iconClassName: '-rotate-90',
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Top Right Radius',
        name: 'borderTopRightRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderTopRightRadiusUnit',
        selectLabel: 'Unit',
        icon: SquareRoundCornerIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Bottom Left Radius',
        name: 'borderBottomLeftRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderBottomLeftRadiusUnit',
        selectLabel: 'Unit',
        icon: SquareRoundCornerIcon,
        iconClassName: '-rotate-180',
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Bottom Right Radius',
        name: 'borderBottomRightRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderBottomRightRadiusUnit',
        selectLabel: 'Unit',
        icon: SquareRoundCornerIcon,
        iconClassName: 'rotate-90',
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
    ],
  },
]

// For backwards compatibility, flatten groups into components
export const AppearanceComponents = AppearanceGroups.flatMap((group) => group.components)
