import { z } from 'zod'
import { MoveRight, MoveLeft, MoveUp, MoveDown, Space, ArrowLeftFromLineIcon, ArrowRightFromLineIcon, ArrowUpFromLineIcon, ArrowDownFromLineIcon, ArrowLeftToLineIcon, ArrowRightToLineIcon, ArrowUpToLineIcon, ArrowDownToLineIcon, UnfoldHorizontalIcon, UnfoldVerticalIcon } from 'lucide-react'

export const zSpacingSchema = z.object({
  marginInlineStart: z.number().optional(),
  marginInlineEnd: z.number().optional(),
  marginBlockStart: z.number().optional(),
  marginBlockEnd: z.number().optional(),
  marginInlineStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginInlineEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginBlockStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginBlockEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingInlineStart: z.number().optional(),
  paddingInlineEnd: z.number().optional(),
  paddingBlockStart: z.number().optional(),
  paddingBlockEnd: z.number().optional(),
  paddingInlineStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingInlineEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingBlockStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingBlockEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  gapX: z.number().optional(),
  gapY: z.number().optional(),
  gapXUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  gapYUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
})

export type SpacingSchema = z.infer<typeof zSpacingSchema>

export const SpacingGroups = [
  {
    legend: 'Margin',
    components: [
      {
        label: 'Inline Start',
        name: 'marginInlineStart',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'marginInlineStartUnit',
        selectLabel: 'Unit',
        icon: ArrowLeftFromLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Inline End',
        name: 'marginInlineEnd',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'marginInlineEndUnit',
        selectLabel: 'Unit',
        icon: ArrowRightFromLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Block Start',
        name: 'marginBlockStart',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'marginBlockStartUnit',
        selectLabel: 'Unit',
        icon: ArrowUpFromLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Block End',
        name: 'marginBlockEnd',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'marginBlockEndUnit',
        selectLabel: 'Unit',
        icon: ArrowDownFromLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
    ]
  },
  {
    legend: 'Padding',
    components: [
      {
        label: 'Padding Inline Start',
        name: 'paddingInlineStart',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'paddingInlineStartUnit',
        selectLabel: 'Unit',
        icon: ArrowLeftToLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Padding Inline End',
        name: 'paddingInlineEnd',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'paddingInlineEndUnit',
        selectLabel: 'Unit',
        icon: ArrowRightToLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Padding Block Start',
        name: 'paddingBlockStart',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'paddingBlockStartUnit',
        selectLabel: 'Unit',
        icon: ArrowUpToLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Padding Block End',
        name: 'paddingBlockEnd',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'paddingBlockEndUnit',
        selectLabel: 'Unit',
        icon: ArrowDownToLineIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
    ]
  },
  {
    legend: 'Gap',
    components: [
      {
        label: 'Gap X',
        name: 'gapX',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'gapXUnit',
        selectLabel: 'Unit',
        icon: UnfoldHorizontalIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Gap Y',
        name: 'gapY',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'gapYUnit',
        selectLabel: 'Unit',
        icon: UnfoldVerticalIcon,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
    ]
  },
]

// For backwards compatibility, flatten groups into components
export const SpacingComponents = SpacingGroups.flatMap((group) => group.components)
