import { z } from 'zod'

export const zSpacingSchema = z.object({
  marginInlineStart: z.number().optional(),
  marginInlineEnd: z.number().optional(),
  marginBlockStart: z.number().optional(),
  marginBlockEnd: z.number().optional(),
  marginInlineStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginInlineEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginBlockStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  marginBlockEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingInlineStart: z.number().optional(),
  paddingInlineEnd: z.number().optional(),
  paddingBlockStart: z.number().optional(),
  paddingBlockEnd: z.number().optional(),
  paddingInlineStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingInlineEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingBlockStartUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  paddingBlockEndUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  gapX: z.number().optional(),
  gapY: z.number().optional(),
  gapXUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  gapYUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
})

export type SpacingSchema = z.infer<typeof zSpacingSchema>

export const SpacingComponents = [
  {
    label: 'Margin Inline Start',
    name: 'marginInlineStart',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'marginInlineStartUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Margin Inline End',
    name: 'marginInlineEnd',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'marginInlineEndUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Margin Block Start',
    name: 'marginBlockStart',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'marginBlockStartUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Margin Block End',
    name: 'marginBlockEnd',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'marginBlockEndUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Padding Inline Start',
    name: 'paddingInlineStart',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'paddingInlineStartUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Padding Inline End',
    name: 'paddingInlineEnd',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'paddingInlineEndUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Padding Block Start',
    name: 'paddingBlockStart',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'paddingBlockStartUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Padding Block End',
    name: 'paddingBlockEnd',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'paddingBlockEndUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Gap X',
    name: 'gapX',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'gapXUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
  {
    label: 'Gap Y',
    name: 'gapY',
    type: 'inputWithOptions',
    inputType: 'number',
    placeholder: '0',
    defaultValue: 0,
    selectName: 'gapYUnit',
    options: [
      { label: 'px', value: 'px' },
      { label: 'em', value: 'em' },
      { label: 'rem', value: 'rem' },
      { label: 'vw', value: 'vw' },
      { label: 'vh', value: 'vh' },
    ],
  },
]
