import {
  IconBorderStyle2,
  IconPaint,
  IconRadiusBottomLeft,
  IconRadiusBottomRight,
  IconRadiusTopLeft,
  IconRadiusTopRight,
} from '@tabler/icons-react'
import { MinusIcon, PaintBucketIcon } from 'lucide-react'
import { z } from 'zod'

import { FormComponent, GroupedComponent } from '../types'

export const zAppearanceSchema = z.object({
  backgroundColor: z.string().optional(),
  borderColor: z.string().optional(),
  borderWidth: z.number().optional(),
  borderStyle: z.enum(['solid', 'dashed', 'dotted', 'double', 'groove', 'ridge', 'inset', 'outset']).optional(),
  borderTopLeftRadius: z.number().optional(),
  borderTopRightRadius: z.number().optional(),
  borderBottomLeftRadius: z.number().optional(),
  borderBottomRightRadius: z.number().optional(),
  borderTopLeftRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderTopRightRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderBottomLeftRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
  borderBottomRightRadiusUnit: z.enum(['px', 'em', 'rem', 'vw', 'vh']).optional(),
})

export type AppearanceSchema = z.infer<typeof zAppearanceSchema>

export const AppearanceGroups: (FormComponent | GroupedComponent)[] = [
  {
    label: 'Background Color',
    name: 'backgroundColor',
    type: 'color',
    inputType: 'color',
    icon: PaintBucketIcon,
    placeholder: '#000000',
    defaultValue: '#000000',
  },
  {
    name: 'borderGroup',
    label: 'Border',
    groups: [
      {
        label: 'Border Color',
        name: 'borderColor',
        type: 'color',
        inputType: 'color',
        icon: IconPaint,
        placeholder: '#000000',
        defaultValue: '#000000',
      },
      {
        label: 'Border Width',
        name: 'borderWidth',
        type: 'input',
        inputType: 'number',
        icon: MinusIcon,
        placeholder: '0',
        defaultValue: 0,
        min: 0,
      },
      {
        label: 'Border Style',
        name: 'borderStyle',
        type: 'select',
        defaultValue: 'solid',
        icon: IconBorderStyle2,
        options: [
          { label: 'Solid', value: 'solid' },
          { label: 'Dashed', value: 'dashed' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'Double', value: 'double' },
          { label: 'Groove', value: 'groove' },
          { label: 'Ridge', value: 'ridge' },
          { label: 'Inset', value: 'inset' },
          { label: 'Outset', value: 'outset' },
        ],
      },
    ],
  },
  {
    label: 'Border Radius',
    name: 'borderRadiusGroup',
    groups: [
      {
        label: 'Border Top Left Radius',
        name: 'borderTopLeftRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderTopLeftRadiusUnit',
        selectLabel: 'Unit',
        icon: IconRadiusTopLeft,
        hideLabel: true,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Top Right Radius',
        name: 'borderTopRightRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderTopRightRadiusUnit',
        selectLabel: 'Unit',
        icon: IconRadiusTopRight,
        hideLabel: true,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Bottom Left Radius',
        name: 'borderBottomLeftRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderBottomLeftRadiusUnit',
        selectLabel: 'Unit',
        icon: IconRadiusBottomLeft,
        hideLabel: true,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
      {
        label: 'Border Bottom Right Radius',
        name: 'borderBottomRightRadius',
        type: 'inputWithOptions',
        inputType: 'number',
        placeholder: '0',
        defaultValue: 0,
        selectName: 'borderBottomRightRadiusUnit',
        selectLabel: 'Unit',
        icon: IconRadiusBottomRight,
        hideLabel: true,
        options: [
          { label: 'px', value: 'px' },
          { label: 'em', value: 'em' },
          { label: 'rem', value: 'rem' },
          { label: 'vw', value: 'vw' },
          { label: 'vh', value: 'vh' },
        ],
      },
    ],
  },
]
