import { z } from 'zod/v4'

export const zTS_TYPES = z
  .union([
    z.literal('string'),
    z.literal('number'),
    z.literal('boolean'),
    z.literal('array'),
    z.literal('object'),
    z.literal('function'),
  ])
  .nullable()

export type TS_TYPES = z.infer<typeof zTS_TYPES>

export const zCoralNameSchema = z.string().regex(/^[a-zA-Z_$][0-9a-zA-Z_$]*$/)

export const zElementSchema = z
  .union([
    z.literal('h1'),
    z.literal('h2'),
    z.literal('h3'),
    z.literal('h4'),
    z.literal('h5'),
    z.literal('h6'),
    z.literal('p'),
    z.literal('span'),
    z.literal('a'),
    z.literal('img'),
    z.literal('ul'),
    z.literal('li'),
    z.literal('ol'),
    z.literal('dl'),
    z.literal('dt'),
    z.literal('dd'),
    z.literal('nav'),
    z.literal('div'),
    z.literal('section'),
    z.literal('footer'),
    z.literal('header'),
    z.literal('button'),
    z.literal('input'),
    z.literal('form'),
    z.literal('textarea'),
    z.literal('select'),
    z.literal('option'),
    z.literal('table'),
    z.literal('tr'),
    z.literal('td'),
    z.literal('th'),
    z.literal('thead'),
    z.literal('tbody'),
    z.literal('tfoot'),
    z.literal('caption'),
    z.literal('time'),
    z.literal('article'),
    z.literal('aside'),
    z.literal('main'),
    z.literal('figure'),
    z.literal('figcaption'),
    z.literal('strong'),
    z.literal('em'),
    z.literal('code'),
    z.literal('pre'),
    z.literal('blockquote'),
    z.literal('hr'),
    z.literal('br'),
    z.literal('label'),
    z.literal('fieldset'),
    z.literal('legend'),
    z.literal('audio'),
    z.literal('video'),
    z.literal('source'),
    z.literal('canvas'),
    z.literal('text'),
    z.literal('svg'),
    z.literal('circle'),
    z.literal('rect'),
    z.literal('path'),
    z.literal('ellipse'),
    z.literal('polygon'),
    z.literal('line'),
    z.literal('polyline'),
    z.literal('g'),
    z.literal('defs'),
    z.literal('use'),
    z.literal('b'),
    z.literal('i'),
    z.literal('u'),
    z.literal('s'),
    z.literal('small'),
    z.literal('mark'),
    z.literal('abbr'),
    z.literal('cite'),
    z.literal('kbd'),
    z.literal('samp'),
    z.literal('var'),
    z.literal('sub'),
    z.literal('sup'),
  ])
  .default('div')

export type CoralElementType = z.infer<typeof zElementSchema>
