/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConvertRouteImport } from './routes/convert'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgsOrgIdIndexRouteImport } from './routes/orgs/$orgId/index'
import { Route as OrgsOrgIdLibrariesLibraryIdIndexRouteImport } from './routes/orgs/$orgId/libraries/$libraryId/index'
import { Route as OrgsOrgIdLibrariesLibraryIdTokensRouteImport } from './routes/orgs/$orgId/libraries/$libraryId/tokens'
import { Route as OrgsOrgIdLibrariesLibraryIdCssResetRouteImport } from './routes/orgs/$orgId/libraries/$libraryId/css-reset'
import { Route as OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRouteImport } from './routes/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'

const ConvertRoute = ConvertRouteImport.update({
  id: '/convert',
  path: '/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdIndexRoute = OrgsOrgIdIndexRouteImport.update({
  id: '/orgs/$orgId/',
  path: '/orgs/$orgId/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgsOrgIdLibrariesLibraryIdIndexRoute =
  OrgsOrgIdLibrariesLibraryIdIndexRouteImport.update({
    id: '/orgs/$orgId/libraries/$libraryId/',
    path: '/orgs/$orgId/libraries/$libraryId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgIdLibrariesLibraryIdTokensRoute =
  OrgsOrgIdLibrariesLibraryIdTokensRouteImport.update({
    id: '/orgs/$orgId/libraries/$libraryId/tokens',
    path: '/orgs/$orgId/libraries/$libraryId/tokens',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgIdLibrariesLibraryIdCssResetRoute =
  OrgsOrgIdLibrariesLibraryIdCssResetRouteImport.update({
    id: '/orgs/$orgId/libraries/$libraryId/css-reset',
    path: '/orgs/$orgId/libraries/$libraryId/css-reset',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute =
  OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRouteImport.update({
    id: '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit',
    path: '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/orgs/$orgId': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/css-reset': typeof OrgsOrgIdLibrariesLibraryIdCssResetRoute
  '/orgs/$orgId/libraries/$libraryId/tokens': typeof OrgsOrgIdLibrariesLibraryIdTokensRoute
  '/orgs/$orgId/libraries/$libraryId': typeof OrgsOrgIdLibrariesLibraryIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit': typeof OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/orgs/$orgId': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/css-reset': typeof OrgsOrgIdLibrariesLibraryIdCssResetRoute
  '/orgs/$orgId/libraries/$libraryId/tokens': typeof OrgsOrgIdLibrariesLibraryIdTokensRoute
  '/orgs/$orgId/libraries/$libraryId': typeof OrgsOrgIdLibrariesLibraryIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit': typeof OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/convert': typeof ConvertRoute
  '/orgs/$orgId/': typeof OrgsOrgIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/css-reset': typeof OrgsOrgIdLibrariesLibraryIdCssResetRoute
  '/orgs/$orgId/libraries/$libraryId/tokens': typeof OrgsOrgIdLibrariesLibraryIdTokensRoute
  '/orgs/$orgId/libraries/$libraryId/': typeof OrgsOrgIdLibrariesLibraryIdIndexRoute
  '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit': typeof OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/convert'
    | '/orgs/$orgId'
    | '/orgs/$orgId/libraries/$libraryId/css-reset'
    | '/orgs/$orgId/libraries/$libraryId/tokens'
    | '/orgs/$orgId/libraries/$libraryId'
    | '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/convert'
    | '/orgs/$orgId'
    | '/orgs/$orgId/libraries/$libraryId/css-reset'
    | '/orgs/$orgId/libraries/$libraryId/tokens'
    | '/orgs/$orgId/libraries/$libraryId'
    | '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
  id:
    | '__root__'
    | '/'
    | '/convert'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/libraries/$libraryId/css-reset'
    | '/orgs/$orgId/libraries/$libraryId/tokens'
    | '/orgs/$orgId/libraries/$libraryId/'
    | '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertRoute: typeof ConvertRoute
  OrgsOrgIdIndexRoute: typeof OrgsOrgIdIndexRoute
  OrgsOrgIdLibrariesLibraryIdCssResetRoute: typeof OrgsOrgIdLibrariesLibraryIdCssResetRoute
  OrgsOrgIdLibrariesLibraryIdTokensRoute: typeof OrgsOrgIdLibrariesLibraryIdTokensRoute
  OrgsOrgIdLibrariesLibraryIdIndexRoute: typeof OrgsOrgIdLibrariesLibraryIdIndexRoute
  OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute: typeof OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/convert': {
      id: '/convert'
      path: '/convert'
      fullPath: '/convert'
      preLoaderRoute: typeof ConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/': {
      id: '/orgs/$orgId/'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof OrgsOrgIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/libraries/$libraryId/': {
      id: '/orgs/$orgId/libraries/$libraryId/'
      path: '/orgs/$orgId/libraries/$libraryId'
      fullPath: '/orgs/$orgId/libraries/$libraryId'
      preLoaderRoute: typeof OrgsOrgIdLibrariesLibraryIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/libraries/$libraryId/tokens': {
      id: '/orgs/$orgId/libraries/$libraryId/tokens'
      path: '/orgs/$orgId/libraries/$libraryId/tokens'
      fullPath: '/orgs/$orgId/libraries/$libraryId/tokens'
      preLoaderRoute: typeof OrgsOrgIdLibrariesLibraryIdTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/libraries/$libraryId/css-reset': {
      id: '/orgs/$orgId/libraries/$libraryId/css-reset'
      path: '/orgs/$orgId/libraries/$libraryId/css-reset'
      fullPath: '/orgs/$orgId/libraries/$libraryId/css-reset'
      preLoaderRoute: typeof OrgsOrgIdLibrariesLibraryIdCssResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit': {
      id: '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
      path: '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
      fullPath: '/orgs/$orgId/libraries/$libraryId/components/$componentId/edit'
      preLoaderRoute: typeof OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertRoute: ConvertRoute,
  OrgsOrgIdIndexRoute: OrgsOrgIdIndexRoute,
  OrgsOrgIdLibrariesLibraryIdCssResetRoute:
    OrgsOrgIdLibrariesLibraryIdCssResetRoute,
  OrgsOrgIdLibrariesLibraryIdTokensRoute:
    OrgsOrgIdLibrariesLibraryIdTokensRoute,
  OrgsOrgIdLibrariesLibraryIdIndexRoute: OrgsOrgIdLibrariesLibraryIdIndexRoute,
  OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute:
    OrgsOrgIdLibrariesLibraryIdComponentsComponentIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
