export const EXPORT_SPEC = 'EXPORT_SPEC'
export const EXPORT_SPEC_STARTED = 'EXPORT_SPEC_STARTED'
export const EXPORT_SPEC_SUCCESS = 'EXPORT_SPEC_SUCCESS'
export const EXPORT_SPEC_ERROR = 'EXPORT_SPEC_ERROR'

export const IMPORT_SPEC = 'IMPORT_SPEC'
